### ISSUE TITLE
Tabslist color formatting broken on older versions

### ISSUE THREAD

**Issue by Column01** [CodeCrafter47/BungeeTabListPlus#665] opened 2021-12-12 21:09 UTC
When using the custom tab list on older versions of Minecraft, it appears the formatting is broken. We're running the latest snapshot of BTLP (3.5.0)

We use a custom version of BungeeCord to allow for 1.7.10 forge servers to work with the proxy, and recently we updated to the 1.18 version of this fork (which just merged the BungeeCord changes...) and it appears to have broken our tab list.

Here is what it looks like right now (no header/footer is normal obviously but colors should be there):
![image](https://user-images.githubusercontent.com/26526649/145729298-4c55cb73-e340-4a72-bfd0-e20c1c6fc541.png)

And here is what it's supposed to look like:
![image](https://user-images.githubusercontent.com/26526649/145729312-7a2a0cd4-9531-40c1-b133-b6e335496d89.png)

Here is what's in the config:
https://gist.github.com/c12277b0c260954eb42942ea22b19399

Any help figuring this out is appreciated! 😄

**Comment by Column01** [comment] 2021-12-12 21:21
Standby: Might have forgotten the bridge plugin

**Comment by Column01** [comment] 2021-12-12 21:36
Bridge is installed and it seems to still be an issue

**Comment by Column01** [comment] 2021-12-12 21:39
No errors in either console as far as I can see

**Comment by Andre601** [comment] 2021-12-12 21:41
This is just my personal view on things, but I feel like 1.7 should really not be supported... at all.
It's extremely old, has bugs and eyploits larger than the new 1.18 world height and generally is just limiting in various ways.

But... if you really want to keep 1.7 support for whatever weird reason, you may need to make a separate tab list for 1.7, or disable it entirely for that version, since there are a few minor drawbacks regarding this version such as [requiring the tab to have the same size as configured in the config](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/FAQ#i-get-size-80-defined-in-defaultyml-is-not-supported-by-client)

Also, on a final note: It would be better to just edit your original comment here as constantly posting new comments is just spamming CodeCrafter's mailbox and the log channel on the Discord.

**Comment by Column01** [comment] 2021-12-12 21:52
> This is just my personal view on things, but I feel like 1.7 should really not be supported... at all.

Like I said in my original post, I haven't checked other versions and I'm willing to bet it's not isolated to 1.7 and is likely to do with the changes to how colours work in recent Minecraft versions. Whether it should be supported or not is up for debate, but the fact there are entire sections and features dedicated to making a tab list for older versions clearly shows support is intentional.

> there are a few minor drawbacks regarding this version such as [requiring the tab to have the same size as configured in the config](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/FAQ#i-get-size-80-defined-in-defaultyml-is-not-supported-by-client)

This is not an issue for me as I have already set up the tab list to work around this limitation. Up until I updated to the snapshot it worked fine

> It would be better to just edit your original comment here as constantly posting new comments is just spamming CodeCrafter's mailbox and the log channel on the Discord.

I'm inclined to agree, however as an active maintainer of reasonably sized software (with a discord log of issues and their comments) IDC if I get a bunch of emails/pings on an issue if it's a genuine issue with the software. If he had an issue with it, let him tell me not to comment multiple times without editing. The updates I gave were relevant to the discussion and my process for tracking down the cause so I felt they were justifiably posted so that it's clear I'm not just posting an issue without actually investigating if it was user error first.

**Comment by Andre601** [comment] 2021-12-12 22:03
> Like I said in my original post, I haven't checked other versions and I'm willing to bet it's not isolated to 1.7 and is likely to do with the changes to how colours work in recent Minecraft versions. Whether it should be supported or not is up for debate, but the fact there are entire sections and features dedicated to making a tab list for older versions clearly shows support is intentional.

I doubt the issue is existing on other versions. Normal chat colour codes have been supported for ages and BungeeCord would never just remove support for it unless Minecraft really got rid of it themself, which is unlikely.
Also, BTLP does support the 24-Bit HEX colours introduced in MC 1.16 and has worked really consistently in later versions, including 1.18 from what we heard so far on our Discord, so again I doubt this issue exists outside of 1.7

Also, the fact something exist doesn't necessarily mean it is officially supported.
It could be something from when 1.7 was the latest release and when 1.8 came around, introducing some significant changes. So rather than something that was added to support 1.7 was it perhaps something that god added to support transitioning from 1.7 to 1.8?
Either way, this is nothing of importance here.



> I'm inclined to agree, however as an active maintainer of reasonably sized software (with a discord log of issues and their comments) IDC if I get a bunch of emails/pings on an issue if it's a genuine issue with the software. If he had an issue with it, let him tell me not to comment multiple times without editing. The updates I gave were relevant to the discussion and my process for tracking down the cause so I felt they were justifiably posted so that it's clear I'm not just posting an issue without actually investigating if it was user error first.

Fair enough, tho it wouldn't have made much of a difference if you just edited your original comment, since CodeCrafter didn't respond so far you could assume he didn't read it yet, so you would've had time to update the comment.
But the points you made do make sense. Only thing is that how someone perceives stuff is different. While you might not mind a lot of e-mails/notifications would others do. It's always up to the person to decide.

Again, those are my personal points here. CodeCrafter could - and probably will - have his own reasons and points to make here, so you can feel free to ignore mine if you like.

**Comment by Column01** [comment] 2021-12-12 22:10
> It could be something from when 1.7 was the latest release and when 1.8 came around, introducing some significant changes. So rather than something that was added to support 1.7 was it perhaps something that god added to support transitioning from 1.7 to 1.8?

If that's the case why is it still included 10 major revisions of the game later? If it wasn't meant to be supported it should at the very least be marked deprecated

Also, It should be noted that we had to use a feature that PaperMC added to Waterfall which extends the max number of Plugin channels via a config option. I set it to 256 channels (default is 128). Unfortunately, I cannot test BTLP without more plugin channels as that server is directly affected by the issue that caused the option to be added... This could very well be related since BTLP uses a plugin channel for sending the data to the server, however, both ends (proxy and server) show no errors when registering the bridge channels or any errors during startup.

**Comment by Andre601** [comment] 2021-12-12 22:16
> If that's the case why is it still included 10 major revisions of the game later? If it wasn't meant to be supported it should at the very least be marked deprecated

1. It doesn't break existing stuff nor needs maintenance to be kept functioning
2. People like you still use this ancient version so... there is that
3. Have fun talking about deprecating and removing stuff with md_5... He sure would love to do that in the Spigot and BungeeCord API /s

There can be several reasons, including that it is actually supported by CodeCrafter for some odd reason, but my personal guess is that he never really bothered to get rid of it. He added it, left it and since it doesn't cause issues in BTLP so far, he never bothered to deal with it again...

**Comment by Villmarksjenta** [comment] 2021-12-12 22:28
Since BungeeTablistPlus specifically says "Minecraft 1.8 or newer works out of the box." and if I understood correctly, the server where the colors are failing is 1.7, there might be bugs including color failure.

I saw Andre mentioning seperate tablist for 1.7. Did you try that? there is a guide here: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/FAQ#how-to-create-a-separate-tab-list-configuration-for-17x-players

Also, which bridge plugin and version of that are you using?

**Comment by Column01** [comment] 2021-12-12 22:43
I'm using 3.5.0 snapshot and the bukkit bridge for that version (the server is running Thermos)

As for trying a separate tabslist for 1.7, that feature doesn't change how the tabslist works, only that it only shows to older clients so I doubt color issues will go away with a separate tab list

**Comment by Villmarksjenta** [comment] 2021-12-12 22:52
> I'm using 3.5.0 snapshot and the bukkit bridge for that version (the server is running Thermos)

I believe for forge you need to use SpongeBridge 3.5.0. I don't remember exactly how forge works

> As for trying a separate tabslist for 1.7, that feature doesn't change how the tabslist works, only that it only shows to older clients so I doubt color issues will go away with a separate tab list

Hmm ok, it might just be buggy then.. As expected for 1.7 tbh, but I get your point here

**Comment by Column01** [comment] 2021-12-13 01:14
> I believe for forge you need to use SpongeBridge 3.5.0. I don't remember exactly how forge works

SpongeBridge would be for Sponge which is completely separate from forge, I also don't think it's because its 1.7.10 but rather something changed in bungee that broke it

**Comment by Column01** [comment] 2021-12-16 17:41
Any update on this? Still broken :/

**Comment by Villmarksjenta** [comment] 2021-12-16 21:53
CodeCrafter47 is currently not working on the plugins, and most likely won't fix this issue in the nearest future I am afraid

**Comment by Andre601** [comment] 2021-12-16 22:01
Yes, he, unfortunately, has a lot to do as a student right now and can't afford any free time to tackle this issue as of right now.
So the best we can hope for is that he will find some free time soon, or for someone to be able to PR a possible fix, that gets accepted.

So your patience is highly apreciated.

**Comment by Column01** [comment] 2021-12-19 02:26
I took the suggestion for now and made a custom tabslist for 1.7.10 that removes colours, would very much like to get this fixed when possible but I'll wait patiently :D

**Comment by CodeCrafter47** [comment] 2021-12-23 15:21
I've taken a look at it. I think the issue has been introduces by 86f7add5c51d7be16b6e3ffd24eab5361490fb1e. I recommend you use the version on spigotmc and not the dev-build, until the bug is fixed.

**Closed** 2022-04-01 12:54 UTC
Labels: bug
