### ISSUE TITLE
BungeeTabList shows question marks by names

### ISSUE THREAD

**Issue by Jackv1999** [CodeCrafter47/BungeeTabListPlus#12] opened 2015-01-29 17:34 UTC
For some reason i can't seem to remove these question marks next to each slot in the tab list could you please help? http://prntscr.com/5yl8nf

**Comment by CodeCrafter47** [comment] 2015-01-29 17:45
This is not an issue. The plugin is configured to show the question mark. Check out defaultSkin in config.yml. You can change it to any other skin you like.

**Comment by Jackv1999** [comment] 2015-01-29 18:20
Hey thanks for replying so quickly, but i don't seem to have this in my
config.yml http://prntscr.com/5ylwfk  http://prntscr.com/5ylwww

**Comment by CodeCrafter47** [comment] 2015-01-29 18:58
My mistake - it's in default.yml

**Comment by Jackv1999** [comment] 2015-01-29 19:20
I must have looked through this at least 5 times before i must be blind!
Thank you for your fast replies!

**Comment by Jackv1999** [comment] 2015-01-29 19:39
May i just quickly ask what to set it to so that it's blank? Leaving the
field blank seems to just keep the question mark sign.

**Comment by CodeCrafter47** [comment] 2015-01-30 13:43
There needs to be a skin in every slot. It can't be removed. You can set it to any skin you like, setting it to an invalid skin will cause the plugin to show random steve/ alex skins.

**Comment by sanjay900** [comment] 2015-02-02 08:03
Just make a skin blob of an empty slot and set that - its what i do.

**Comment by Jackv1999** [comment] 2015-03-08 13:38
Hi, I can't get the skins to look the same as the tablist how do i make it
so that it looks like there's no skin there and it's just blank?
http://prntscr.com/6e8dqe

**Comment by sanjay900** [comment] 2015-03-09 21:55
The closest you can do is a gray square - Skins cant be transparent, so its
difficult to make it look like a slot.

**Comment by CodeCrafter47** [comment] 2015-03-28 16:20
Changing the skin is possible, removing not but thats not a bug but a limitation as this is a serverside mod only so I'm closing this now.

**Closed by CodeCrafter47** 2015-03-28 16:20 UTC
Labels: invalid
