### ISSUE TITLE
Heads sometimes out of order

### ISSUE THREAD

**Issue by SubtypeZero** [CodeCrafter47/BungeeTabListPlus#274] opened 2017-09-14 20:17 UTC
Sometimes players join/leave and the tab list heads don't always match up with player names.

![tab](https://user-images.githubusercontent.com/25497312/30453431-7dfbb02c-995e-11e7-8427-5774b42bd2c8.png)

Here's what they should look like:
![correct](https://user-images.githubusercontent.com/25497312/30453533-cfd27a84-995e-11e7-815a-c3f20474674e.png)

These screenshots are from a Sponge server with the Sponge bridge installed. I use LuckPerms to sort players in the tab list by group, then alphabetically.

Here's a link to my config file:  https://pastebin.com/wuhzffME

**Comment by SubtypeZero** [comment] 2017-10-12 00:26
Any ETA on a fix for this?

**Comment by CodeCrafter47** [comment] 2017-10-12 06:24
No ETA, but will probably take some time. I don't see this as a very important thing to fix as it happens only rarely (only in dynamic size mode if all players on one server or only local players shown, and even then it's correct most of the time).

**Comment by marx1** [comment] 2017-10-15 04:39
I've actually had a couple of people say something about this, For me it triggers my OCD and makes me want to rip it out.

**Comment by SubtypeZero** [comment] 2017-10-22 01:58
This actually happens quite often. I do hope that you're able to look into fixing this soon. It would be much appreciated as I don't have any plans to change the formatting of my tab list and I rather like the simple look of it.

**Comment by dlaverick** [comment] 2017-11-19 15:27
This happens on my UHC server when using hearts health bar using Upd4tings UHC Reloaded plugin. Happens game.

**Comment by SubtypeZero** [comment] 2017-12-15 00:39
It's been three months now since reporting this issue. I'd really like to have a fix for this soon. If there's anything preventing this from being fixed, I would be happy to assist in any way I can. I'm getting pretty tired of seeing a malformed tab list every time I check to see who is online.

**Comment by CodeCrafter47** [comment] 2017-12-15 06:29
The problem is somewhere in [AbstractTabListLogic.java](https://github.com/CodeCrafter47/BungeeTabListPlus/blob/master/bungee/src/main/java/codecrafter47/bungeetablistplus/tablisthandler/logic/AbstractTabListLogic.java), which serves as an abstraction layer. That file contains over 1000 lines of code, and even though I've written it I don't understand how I works. That it works correctly is mostly validated by lots of unit tests, lots of the test cases have generated by recording what happens on real servers.

My plan is to eventually replace the entire file with something that has less bugs and is easier to maintain. This will be done along with some other structural changes which still require some work.

**Comment by SubtypeZero** [comment] 2017-12-15 22:15
I believe it only happens when people join/leave, if that helps narrow it down. I know you would really like to replace that class completely, but I'd like to get the bug sorted out first.

**Comment by CodeCrafter47** [comment] 2017-12-17 09:13
To find the Bug you first need to collect the data required for reproducing it. For that purpose a special version of the plugin exists: [https://ci.codecrafter47.de/job/BungeeTabListPlus/695/artifact/bootstrap-bungee-debug/target/BungeeTabListPlus-2.8.0-debug.jar](https://ci.codecrafter47.de/job/BungeeTabListPlus/695/artifact/bootstrap-bungee-debug/target/BungeeTabListPlus-2.8.0-debug.jar).
When running it'll create an `eventLog` folder below the `BungeeTabListPlus` folder, and there it will save lots of files (one per user and session). Make the bug happen while running that version. Then the created log files can be used to find the bug. Make sure you properly shut down BungeeCord before copying any of the log file.
A lot of these log files are [already in use for automated testing](https://github.com/CodeCrafter47/BungeeTabListPlus/tree/master/bungee/src/test/resources). You can either send the created log files to me or run the test yourself by placing the log files in the folder with the others and adding their names to `TestRealWorldExamples.java`.

**Comment by CodeCrafter47** [comment] 2020-01-17 21:06
This issue should be fixed in the[ latest dev-build](https://ci.codecrafter47.de/job/BungeeTabListPlus/).

**Closed by CodeCrafter47** 2020-01-17 21:06 UTC
Labels: bug
