### ISSUE TITLE
Custom variable blinking/flickering at random in tablist

### ISSUE THREAD

**Issue by Foorack** [CodeCrafter47/BungeeTabListPlus#224] opened 2017-06-05 18:18 UTC
I have written a plugin which registers 1 custom variable. The variable reports on the AFK status on a player. The function `getReplacement` returns either "true" or "false". In the config file the following customPlaceholder is defined:

![image](https://cloud.githubusercontent.com/assets/5008081/26796255/17356fce-4a29-11e7-901a-de454ddfe2f4.png)

The ${afk_tag} is used next to each players name. In tab list, the result is that the AFK tag repeatedly disappears and reappears at a constant but random interval. Reloading BTLP changes this interval, if the reload is timed correctly then at luck it works and is shown all the time.

For debug purposes, I added the original tag to see if the players status was constantly changing but no, the value "true" repeatedly appears and disappears. Changing the tablistUpdateInterval from 0.5 to 1 seems to make a bit more stable but it is still blinking, just with a lower interval.

Here is a gif of it "in action". Running latest version of BTLP and BungeeCord. Java 8. Minecraft 1.11.2
![image](https://i.imgur.com/R2Sw1xo.gif)

**Comment by CodeCrafter47** [comment] 2017-06-17 16:47
Can you check whether the issue is fixed using the [latest dev-build](http://ci.codecrafter47.de/job/BungeeTabListPlus/)?

**Comment by Foorack** [comment] 2017-06-30 13:33
@CodeCrafter47 Nope, and vault variables are broken as well on latest version.

**Comment by CodeCrafter47** [comment] 2017-07-01 06:36
You need to install the latest dev-build on BungeeCord and Bukkit, otherwise the bridge won't work at all.

**Comment by finalchild** [comment] 2017-08-14 00:39
My server too has a blinking scoreboard.

**Comment by CodeCrafter47** [comment] 2017-08-14 08:06
This issue is about the tab list, not the scoreboard. Also I consider this issue to be fixed as of version 2.8.0 of BungeeTabListPlus. If you are experiencing any issues with the latest version of the plugin please open a new issue.

**Closed by CodeCrafter47** 2017-08-14 08:06 UTC
Labels: bug
