### ISSUE TITLE
1.8 Players getting disconnected

### ISSUE THREAD

**Issue by Xayanix** [CodeCrafter47/BungeeTabListPlus#112] opened 2016-06-17 13:35 UTC
15:22:10 [SEVERE] [balajosek5] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:643)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:636)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:239)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
    at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:149)
    at codecrafter47.bungeetablistplus.tablisthandler.CustomTabList18.onUpdate(CustomTabList18.java:287)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:113)
    at net.md_5.bungee.protocol.packet.PlayerListItem.handle(PlayerListItem.java:149)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

**Comment by CodeCrafter47** [comment] 2016-06-18 06:31
Which version of BungeeCord are you using?
Are you using any other plugins?

**Comment by Xayanix** [comment] 2016-06-18 07:49
Im using HexagonMC bungee with only Yours plugin and one own created.
18.06.2016 08:32 "Florian Stober" <notifications@github.com> napisał(a):

**Comment by CodeCrafter47** [comment] 2016-06-18 11:44
Is it possible to get a longer stack trance. Especially the next few lines after "Caused by: java.lang.NullPointerException" would be interesting.

**Comment by Xayanix** [comment] 2016-06-18 15:01
I already sent full stack trace.

<https://www.avast.com/pl-pl/c-malware> Brak malware
<https://www.avast.com/pl-pl/c-malware>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-06-18 13:44 GMT+02:00 Florian Stober <notifications@github.com>:

**Comment by CodeCrafter47** [comment] 2016-06-18 15:02
No you didn't. And I can't help you if you don't send the full stack trace.

**Comment by Xayanix** [comment] 2016-06-18 17:08
I am not stupid, lol.



17:35:26 [INFO] [/83.11.186.168:50503] <-> InitialHandler has connected
17:35:26 [INFO] [/92.21.15.207:26928] <-> InitialHandler has connected
17:35:26 [SEVERE] [Laziopl] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
at
io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
at
io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:643)
at
io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
at
io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:636)
at
io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
at io.netty.channel.AbstractChannel.write(AbstractChannel.java:239)
at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:149)
at
codecrafter47.bungeetablistplus.tablisthandler.CustomTabList18.exclude(CustomTabList18.java:186)
at
codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:147)
at
codecrafter47.bungeetablistplus.ResendThread.lambda$run$0(ResendThread.java:119)
at
io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
at
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)
at
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
17:35:26 [INFO] [Laziopl] disconnected with: §fEncoderException :
java.lang.NullPointerException @
io.netty.handler.codec.MessageToByteEncoder:125
17:35:26 [INFO] [Laziopl] -> UpstreamBridge has disconnected
17:35:26 [INFO] [/94.254.241.249:25321] <-> InitialHandler has connected
17:35:26 [INFO] [/109.196.59.40:54731] <-> InitialHandler has connected
17:35:26 [INFO] [Laziopl] <-> DownstreamBridge <-> [csgo] has disconnected
17:35:26 [INFO] [Laziopl] disconnected with: §7Polaczenie z serwerem
zostalo zerwane.
17:35:26 [INFO] [Laziopl] <-> DownstreamBridge <-> [csgo-6] has disconnected
17:35:26 [INFO] [/89.231.94.1:6610] <-> InitialHandler has connected

<https://www.avast.com/pl-pl/c-malware> Nie wykryto malware
<https://www.avast.com/pl-pl/c-malware>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-06-18 17:02 GMT+02:00 Florian Stober <notifications@github.com>:

**Comment by CodeCrafter47** [comment] 2016-06-19 13:47
Maybe there is a longer stack trace somewhere else in your log. The one you provided contains insufficient  information for identifying and fixing the issue.

**Comment by CodeCrafter47** [comment] 2016-07-01 09:55
Is this fixed in version 2.5.1?

**Closed** 2016-11-29 20:02 UTC
