### ISSUE TITLE
An internal error occurred!

### ISSUE THREAD

**Issue by NeglectDream** [CodeCrafter47/BungeeTabListPlus#752] opened 2023-12-29 21:16 UTC
[05:15:08 ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
>java.lang.NoSuchMethodError: net.md_5.bungee.protocol.packet.Team.getDisplayName()Ljava/lang/String;
at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.onTeamPacket(AbstractTabOverlayHandler.java:326) ~[?:?]
at codecrafter47.bungeetablistplus.handler.LowMemoryTabOverlayHandlerImpl.onTeamPacket(LowMemoryTabOverlayHandlerImpl.java:41) ~[?:?]
at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onTeamPacket(AbstractPacketHandler.java:43) ~[?:?]
at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onTeamPacket(AbstractPacketHandler.java:43) ~[?:?]
at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:52) ~[?:?]
at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:30) ~[?:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:bc2e5e7:unknown]
at java.lang.Thread.run(Thread.java:855) [?:1.8.0_382]

**Comment by Andre601** [comment] 2023-12-29 22:03
Duplicate of #751 most likely.

Please use the latest dev build from the CI. Yes, it says 3.6.1, but it's the latest build that should fix this.

**Closed as completed** 2023-12-29 22:15 UTC
