### ISSUE TITLE
Incompatibility with ProtocolSupport.

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#414] opened 2019-03-31 09:22 UTC
Paper dev 597 (Spigot 1.13.2)
Travertine dev 91 (Waterfall/BungeeCord)
ProtocolSupport dev 370
BungeeTabListPlus dev 796

Config - https://paste.ubuntu.com/p/Ty82NWTdVK/
tabList - https://paste.ubuntu.com/p/NKC5C8b78n/

RE: https://github.com/ProtocolSupport/ProtocolSupport/issues/1047
@CodeCrafter47 Any ideas on why BTLP breaks? :(

I use the plugin ProtocolSupport to allow 1.12 and 1.13 clients to connect together. 

On 1.13, I am correctly colored and sorted above all others. I also see the world placeholder for the world I am currently in.
![link](https://i.imgur.com/Vd6qYDC.png)

On 1.12, it does not color me and I am sorted last in the list. I also do not see the world placeholder for the world I am currently in. As well as apparently other players who are on 1.13 while I'm on 1.12 see me unsorted with a white name too.
![link2](https://i.imgur.com/S0TsRx1.png)

There are no errors whatsoever in either the proxy or server console as far as I looked.

**Comment by CodeCrafter47** [comment] 2019-03-31 09:43
Player order, as well as prefix and world placeholder use information from the BungeeTabListPlus_BukkitBridge plugin. BungeeTabListPlus (bungee) communicates with the bridge plugin (bukkit/ spigot) using plugin messages. The ProtocolSupport plugin might be changing plugin messages in a way that prevents this communication.

**Comment by mibby** [comment] 2019-04-01 07:04
@Shevchik Any ideas what ProtocolSupport may be changing in the plugin message? :(

**Comment by mibby** [comment] 2019-04-04 04:40
@CodeCrafter47 https://github.com/ProtocolSupport/ProtocolSupport/issues/1050#issuecomment-478504233

> All < 1.13 plugin channel will have l: appended at start and all other invalid symbols removed.
Your plugin will have to be adapted to use transformed channel name.
I will try to bring back support of 1.13 formatted channel names for < 1.13, but that will take time to do properly.

Any possible workaround? :(

**Comment by CodeCrafter47** [comment] 2019-04-04 07:43
You'll have to wait until the issue is fixed in ProtocolSupport. While you wait for that to happen, you might be able to reduce its impact by changing your configuration so it uses less placeholders that depend on the bridge plugin. E.g. Don't display the world, if you're using LuckPerms replace `${player vault_prefix}` with `${player luckperms_prefix}`, you can display a different tab list layout depending on the version of the player (see <https://github.com/CodeCrafter47/BungeeTabListPlus/issues/139>).

**Closed** 2020-04-20 03:12 UTC
