### ISSUE TITLE
Tablist per server

### ISSUE THREAD

**Issue by ghost** [CodeCrafter47/BungeeTabListPlus#131] opened 2016-09-25 21:00 UTC
When I configure a tablist to work on specific server, then when I switch to another server I still have the old tablist.

**Comment by CodeCrafter47** [comment] 2016-09-26 10:39
As far as I can tell that works fine.

Can you check the following things:

1. Make sure you are running the latest version of BungeeTabListPlus (2.6.3). I remember there had been a similar issue in previous versions.

2. Make sure the priorities are set correctly (server specific tab list should have a higher priority than the default) and you don't have any interfering .yml file in the `tabLists` directory. 

3. Note that switching the active tabList may not remove the old header/ footer if switching to a tabList that doesn't have a header/ footer or if the backing servers tablist is shown and there is no tab header/ footer plugin installed on the backing server.

**Comment by CzlowiekKuktas** [comment] 2016-09-26 17:50
But when I switch to a server which doesn't have BTLP tablist, but Bukkit tablist it still shows the BTLP tablist.

**Comment by CodeCrafter47** [comment] 2016-09-26 22:04
Can you put your config files (ideally the entire BungeeTabListPlus directory) in a zip file and upload them somewhere?

Also I'd like to see a screenshot of the output of the `/btlp status` command, ideally once performed when connected to the server that has the BTLP tab list and once connected to the server that shouldn't have it.

**Comment by CzlowiekKuktas** [comment] 2016-09-26 22:09
I simply created a tablist to 1 server using 'showTo'.

**Comment by CodeCrafter47** [comment] 2016-09-26 22:17
If I do that it works correctly, so you're doing something different to how I do. I'm not a magican, I can't tell why there is an issue if all you tell me is that there is an issue. To help you, I need you to give me more information.

**Comment by CzlowiekKuktas** [comment] 2016-09-26 22:19
The tablist stays for 1.7 players.

**Comment by CodeCrafter47** [comment] 2016-09-26 22:33
Well that's helpful. I'll see for it that the issue is fixed with the next update.

**Closed** 2016-11-29 20:00 UTC
