### ISSUE TITLE
[SUGGESTION] Velocity support

### ISSUE THREAD

**Issue by rudde0** [CodeCrafter47/BungeeTabListPlus#606] opened 2020-11-26 08:32 UTC
BungeeTabListPlus should support Velocity proxies imo.

**Comment by CodeCrafter47** [comment] 2020-11-26 09:41
duplicate of #405 

While velocity support would be nice, I do not have the time to work on it. PR's would be welcome.

**Closed by CodeCrafter47** 2020-11-26 09:41 UTC
Labels: duplicate, enhancement
