### ISSUE TITLE
API Problem

### ISSUE THREAD

**Issue by xeq** [CodeCrafter47/BungeeTabListPlus#60] opened 2015-11-29 00:46 UTC
Hello. I've been playing around a little with your API for BungeeTablistPlus.

My Guild plugin provides an api, which allows you to get for example number of someones deaths.

I used your Bukkit Bridge to register my new per player variable on the TabList, showing the result (amount of player deaths)

Here is my code:

public class KillsVariable extends Variable {
	public KillsVariable() {
		// name of the variable without { }
		super("KILLS");
	}

	@Override
	public String getReplacement(Player player) {
		User u = User.get(player);
		
		return "" + u.getRank().getKills();
	}
}

But variable {KILLS} displays some random nickname of players from my server. Every variable that I registered with bukkit bridge, is constant and it usually shows someones nickname . I registered the variable in my onEnable. Can you fix it / help me registering my custom dynamic per-player variables?

**Comment by CodeCrafter47** [comment] 2015-11-29 07:43
The issue is fixed in the latest dev-build. See 3b34f29cae150fecca23e3063658dd8b1e6cb4b0.

**Comment by xeq** [comment] 2015-11-29 15:51
Can you send me the .jar file of this build cuz I've been struggling with maven for 3 hours and it didn't work.

**Comment by CodeCrafter47** [comment] 2015-11-29 16:02
http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/

**Closed** 2015-12-01 20:46 UTC
