### ISSUE TITLE
NoSuchMethodError ,the plugin can't work

### ISSUE THREAD

**Issue by Eustiya** [CodeCrafter47/BungeeTabListPlus#372] opened 2018-07-19 07:26 UTC
`following StackTrace to the developer in order to help resolving the problem
java.lang.NoSuchMethodError: net.md_5.bungee.protocol.packet.Team.getColor()B
    at codecrafter47.bungeetablistplus.tablisthandler.logic.AbstractTabListLogic
.onTeamPacket(AbstractTabListLogic.java:534)
    at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListLogic.onTeamP
acket(TabListLogic.java:112)
    at codecrafter47.bungeetablistplus.tablisthandler.logic.LowMemoryTabListLogi
c.onTeamPacket(LowMemoryTabListLogic.java:38)
    at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListHandler.onTea
mPacket(TabListHandler.java:53)
    at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListHandler.onTea
mPacket(TabListHandler.java:53)
    at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketList
ener.java:56)
    at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketList
ener.java:35)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessa
geDecoder.java:88)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessa
geDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessage
Decoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessage
Decoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecod
er.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDeco
der.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.ja
va:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultCh
annelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPip
eline.java:965)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNi
oByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:64
7)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLo
op.java:582)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:4
99)`

**Comment by CodeCrafter47** [comment] 2018-07-19 15:18
Duplicate of #370 .
I already fixed this issue. Just use the latest dev-build.

**Closed by CodeCrafter47** 2018-07-19 15:18 UTC
