### ISSUE TITLE
Velocity Request

### ISSUE THREAD

**Issue by JustZerooo** [CodeCrafter47/BungeeTabListPlus#728] opened 2023-09-24 18:37 UTC
[18:36:03 ERROR]: Unable to load plugin plugins/BungeeTabListPlus-3.6.1.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file BungeeTabListPlus-3.6.1.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]

**Comment by Andre601** [comment] 2023-09-24 19:32
The plugin is called **Bungee**TabListPlus for a reason. It **only** supports BungeeCord Proxies and not Velocity.

And there most likely won't be any Velocity support either since the API is not only vastly different, but also lacks features that BTLP relies on for functionality.

**Comment by andrewkm** [comment] 2023-09-25 13:09
Velocity would be nice :) API has also improved quite a lot.

**Comment by Phoenix616** [comment] 2023-09-26 12:23
Duplicate of #405

**Closed** 2023-10-21 08:32 UTC
Labels: duplicate
