### ISSUE TITLE
BungeeTabListPlus_BukkitBridge-2.2.8

### ISSUE THREAD

**Issue by KelvinKam** [CodeCrafter47/BungeeTabListPlus#66] opened 2015-12-13 19:30 UTC
BungeeTabListPlus_BukkitBridge-2.2.8 with Essentials and Spigot 1.7.9 spamming error

http://pastebin.com/WpT9q0PE

Please drop PM to me if you need any further information, at spigotmc https://www.spigotmc.org/members/kelvin-kam.4048/

Thank you

**Comment by CodeCrafter47** [comment] 2015-12-14 08:44
Can you provide a link to the version of Essentials you have been using?

**Comment by KelvinKam** [comment] 2015-12-15 16:35
http://dev.bukkit.org/bukkit-plugins/essentials/files/
2.12.1 haha, maybe I should update first (I just know it have update released)

**Comment by Rubbertjuh** [comment] 2016-06-23 10:07
Having the same issue. 
Running EssentialsX 2.0.1
Downgrading to BungeeTabListPlus-2.0.5 worked and fixed the spamming.
Anything I can do about this?

**Comment by CodeCrafter47** [comment] 2016-06-23 10:30
I downloaded EssentialsX 2.0.1 from <https://www.spigotmc.org/resources/essentialsx.9089/>. I did not experience the described issue. I can't fix issues which I can't reproduce.

**Comment by CodeCrafter47** [comment] 2016-12-23 17:08
Closing this issue as it relates to a old version of BungeeTabListPlus. Please open a new issue if the problem can be reproduced with the latest version of the plugin.

**Closed by CodeCrafter47** 2016-12-23 17:08 UTC
