### ISSUE TITLE
Failed to acquire data DataKey and A task raised an exception

### ISSUE THREAD

**Issue by a3539450** [CodeCrafter47/BungeeTabListPlus#682] opened 2022-06-14 01:21 UTC
BungeeCord version: BungeeCord dev build version 1644 , Waterfall-1.19-495 ,Waterfall-1.19-496
BungeeTabListPlus version: 3.4.4, 3.5.0, (Dev Builds))3.6.0-#1118
Server Jar version:  spigot-1.19, paper-1.19-8

Frontend: No tabled content shown,Only one black rectangle
Error stacktrace:https://pastebin.com/s6DjGBAS

**Comment by Andre601** [comment] 2022-06-14 07:26
Duplicate of #679 and #680

Please update to the latest dev build of BTLP.

**Closed** 2022-06-14 10:57 UTC
