### ISSUE TITLE
NameTag visible on invisibility

### ISSUE THREAD

**Issue by andramil** [CodeCrafter47/BungeeTabListPlus#426] opened 2019-05-15 20:20 UTC
Similar bug like in case #422 
If player has invisible effect others can see his nametag. 
Bug appears only on 1.8.x verssion.
All possibles checked - problem caused by BTLP

[Screen](https://i.imgur.com/M3lCJwg.jpg)

**Comment by andramil** [comment] 2019-05-18 10:29
On 1.8.x client verssion. I have 1.8 server with viaversion. If someone enter from 1.9+ version he cant see nametag, but if he play on 1.8 client version he sees it.

**Comment by CodeCrafter47** [comment] 2019-05-20 10:20
I've looked into it and this bug does indeed occur in Minecraft 1.8.x. Further investigation showed that this is a bug in the minecraft client, so there is nothing I as a plugin author can do about it.

**Comment by andramil** [comment] 2019-05-20 10:36
But without BTLP and on older version bug does not occure

**Comment by CodeCrafter47** [comment] 2019-05-20 11:26
It can occur. To modify the tab list, BTLP needs to assign every player to a scoreboard team (can be a different team for each player). If you do that without BTLP (i.e. assign every player to some scoreboard team), then the bug will occur without using BTLP.

**Comment by Zaino60** [comment] 2019-08-21 06:14
Please fix this bug, a lot of servers and players still use 1.8 and this bug is game-breaking

**Comment by xGlenor** [comment] 2019-08-26 01:23
> 
> 
> Please fix this bug, a lot of servers and players still use 1.8 and this bug is game-breaking

I'm joining

**Comment by call911nowplz** [comment] 2019-12-18 21:11
Please fix this issue.

**Comment by CodeCrafter47** [comment] 2019-12-19 10:55
As explained above this is a bug in the Minecraft client. I cannot fix it. Mojang has to fix it. They did fix it. You just need to update.

**Comment by xGlenor** [comment] 2020-07-15 21:37
Something news? The error continues to occur

**Comment by CodeCrafter47** [comment] 2020-07-16 06:42
What news do you expect? It's a bug in minecraft and it has been fixed years ago. If you don't update minecraft you still have the bug. But that's your choice - using an old version of minecraft.

I'm closing this issue as it is not a bug in the plugin.

**Closed by CodeCrafter47** 2020-07-16 06:42 UTC
Labels: bug, wontfix
