### ISSUE TITLE
LuckPerms API Update

### ISSUE THREAD

**Issue by cjm721** [CodeCrafter47/BungeeTabListPlus#294] opened 2017-11-18 23:54 UTC
Looks like LuckPerms API changed
```
18:52:59 [WARNING] [BungeeTabListPlus] Failed to acquire data DataKey(id=luckperms:prefix, scope=Scope(id=bungee:player), type=de.codecrafter47.data.api.TypeToken@7e0bc8a3, parameter=null) from Battery3996
java.lang.NoSuchMethodError: me.lucko.luckperms.api.User.getUserDataCache()Ljava/util/Optional;
    at de.codecrafter47.data.bungee.luckperms.LuckPermsPrefixProvider.apply(LuckPermsPrefixProvider.java:43)
    at de.codecrafter47.data.bungee.luckperms.LuckPermsPrefixProvider.apply(LuckPermsPrefixProvider.java:29)
    at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30)
    at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44)
    at de.codecrafter47.data.bungee.AbstractBungeeDataAccess.get(AbstractBungeeDataAccess.java:42)
    at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40)
    at codecrafter47.bungeetablistplus.managers.DataManager.updateData(DataManager.java:71)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by CodeCrafter47** [comment] 2017-11-19 10:00
Duplicate of #292

**Closed by CodeCrafter47** 2017-11-19 10:00 UTC
